package com.neversion.store.user.infrastructure.in.rest.mapper;

import com.neversion.store.user.domain.model.Role;
import com.neversion.store.user.domain.model.User;
import com.neversion.store.user.domain.model.enums.UserRole;
import com.neversion.store.user.infrastructure.in.rest.dto.UserRequest;
import com.neversion.store.user.infrastructure.in.rest.dto.UserResponse;
import org.springframework.stereotype.Component;

@Component
public class UserRestMapper {

    public User toDomain(UserRequest userRequest) {
        return new User(
            null, // ID is generated by the database
            userRequest.firstName(),
            userRequest.lastName(),
            userRequest.email(),
            userRequest.password(),
            userRequest.phoneNumber(),
            true, // isActive defaults to true for new users
            new Role(null, UserRole.valueOf(userRequest.role().toUpperCase()), null),
            null, // createdAt is generated by the database
            null // updatedAt is generated by the database
        );
    }

    public UserResponse toResponse(User user) {
        UserResponse.RoleResponse roleResponse = new UserResponse.RoleResponse(
            user.role().name().name(),
            user.role().description()
        );
        return new UserResponse(
            user.id(),
            user.firstName(),
            user.lastName(),
            user.email(),
            user.phoneNumber(),
            roleResponse
        );
    }
}
